version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: vrdcoker.azurecr.io/prometheus-custom:latest
    user: root
    container_name: prometheus
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ${WEBAPP_STORAGE_HOME:-./data}/prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    image: vrdcoker.azurecr.io/grafana-custom:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ${WEBAPP_STORAGE_HOME:-./data}/grafana-data:/var/lib/grafana
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    command:
      - '-port=8098'
    volumes:
      - ${WEBAPP_STORAGE_HOME:-./data}/rootfs:/rootfs:ro
      - ${WEBAPP_STORAGE_HOME:-./data}/var/run:/var/run:ro
      - ${WEBAPP_STORAGE_HOME:-./data}/sys:/sys:ro
      - ${WEBAPP_STORAGE_HOME:-./data}/var/lib/docker:/var/lib/docker:ro
      - ${WEBAPP_STORAGE_HOME:-./data}/dev/disk:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    privileged: true
    ports:
      - '9100:9100'
    volumes:
      - ${WEBAPP_STORAGE_HOME:-./data}/proc:/host/proc:ro
      - ${WEBAPP_STORAGE_HOME:-./data}/sys:/host/sys:ro
      - ${WEBAPP_STORAGE_HOME:-./data}/rootfs:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    restart: unless-stopped